# Generated by Django 4.2.5 on 2023-09-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adress', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tranche', models.CharField(default='paiement', max_length=15)),
                ('nouveau_prix', models.DecimalField(decimal_places=2, default='0000', max_digits=10)),
                ('apayer', models.DecimalField(decimal_places=2, default='0000', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tricycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=2000.0, max_digits=19)),
                ('weight', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='uploads/')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tricycleapp.modele')),
            ],
        ),
    ]
