# Generated by Django 4.2.5 on 2023-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tricycleapp', '0003_reservation_phone_reservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
